# Generated by Django 4.1.3 on 2022-12-23 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppEI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liga',
        ),
        migrations.AddField(
            model_name='jugador',
            name='club',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
